export const ERROR_MESSAGES = {
  INVALID_ACCESS_CODE: "Invalid access code",
  EMAIL_ALREADY_EXISTS: "Email already exists",
  MISSING_REQUIRED_FIELDS: "Missing required fields",
  INTERNAL_SERVER_ERROR: "Internal Server Error",
  INVALID_USERNAME_AND_PASSWORD: "Invalid email or password",
  NOT_AUTHETICATED: "Not authenticated",
  INVALID_TOKEN: "Invalid token",
  USER_NOT_FOUND: "User not found",
  COMPANY_NOT_FOUND: "Company not found",
  COMPANY_UPDATE_FAILED: "Failed to update company",
  JOB_CREATE_FAILED: "Failed to create job",
  JOB_NOT_FOUND: "Job not found",
  JOB_UPDATE_FAILED: "Failed to update job",
  JOB_DELETE_FAILED: "Failed to delete job",
  LOCATION_FETCH_FAILED: "Failed to fetch locations",
};
